**Numpy**
Linear cebir kütüphanesidir. Matematiksel işlemleri hızlı kulanılmasında yarar sağlar.Numpy array(dizi) tek boyutlu veya iki boyutlu dizler oluşturabilirler  Veri analizde tek boyutlu listeler vardır  fakat numpy array(dizi) halinde tututğumuzda daha küçük bellekte saklamamızı sağlar.Eğer ben bir listeyi array(dizi) haline getirmek İstiyorsam numpy kütüphanesini kullanabilirim. numpy kullanarak sıfırdan dan da  array elde edebilrim.Yanlız  numpy da ki değerler float değerlerdir.

Kurulumu eğer yoksa :

```

pip install numpy #(jupyter spyder pycharm)
!pip insatll numpy #(colab)

```


Kütüphaneyi bu şekilde çağırabilirsiniz :
`import nupy as np `

 Numpy dizinde ile ilgili daha detaylı veya daha fazla neler yapabileceğiniz inclemek ,ç,n numpy kendi sitesi olan numpy.org ulaşabilirsiniz .
 https://numpy.org/doc/stable/

**List VS Numpy Array**
 Python listeleri ve NumPy dizileri arasındaki farklar:

Veri Tipi: Python listeleri farklı veri tiplerini içerebilirken, NumPy dizileri homojen veri tiplerine sahiptir.

Performans: NumPy dizileri genellikle Python listelerinden daha hızlıdır ve büyük veri setleriyle daha etkili bir şekilde çalışır.

Boyut ve Şekil: NumPy dizileri çok boyutlu olabilirken, Python listeleri yalnızca tek boyutludur. Ayrıca, NumPy dizilerinin şekli değiştirilebilirken, Python listelerinin uzunluğu değiştirilebilir.

İşlevsellik: NumPy, bilimsel ve matematiksel işlemler için özel işlevler sunar ve vektörleştirilmiş işlemleri destekler.

Bellek Kullanımı: NumPy dizileri genellikle Python listelerinden daha düşük bellek tüketir.

NumPy dizileri genellikle bilimsel hesaplamalar, veri işleme ve makine öğrenimi gibi alanlarda tercih edilirken, Python listeleri daha genel amaçlı kullanımlar için daha uygundur.

In [ ]:
liste=[1,2,3]
type(liste)

list

In [ ]:
import numpy as np

In [ ]:
np.array(liste)

array([1, 2, 3])

In [ ]:
matrixliste=[[1,2,3],[4,5,6]]
type(matrixliste)

list

In [ ]:
np.array(matrixliste)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(matrixliste)

list

In [ ]:
matrixliste = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_array = np.array(matrixliste)

print(type(matrixliste))  # <class 'list'>
print(type(matrix_array))  # <class 'numpy.ndarray'>
#Burada anlaşıldığı gibi yeni bir değişken atadığımızda  o zaman type() değişir .

<class 'list'>
<class 'numpy.ndarray'>


***Numpy Array ***

In [ ]:
import numpy as np
a=[1,2,3]
arr=np.array(a)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
x=[[1,2,3],[4,5,6],[7,8,9]]
arr1=np.array(x)

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2=np.array([20,30,40])

In [ ]:
arr2[0]

20

In [ ]:
arr1[1,2]#(satır ,sutün)
# burada sutün veya satır sayısını elimizdekinden daha büyük bir değerler örnek [3,3]gibi hataya düşer dikkat etmemiz gerekir

6

*ones* istediğimiz kadar bir yazdırarak bir dizi yapmamızı sağlar

In [ ]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((8,8))
#iki boyutlu dizilerde kullanbiliriz matrikste iki parantezin içine yazılır

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

*arange* tıpkı pythonda kilisterl gibi işlevi vardır nupy da bu özelliği vardır

In [ ]:
np.arange(0,10) #(Başlama değeri ,bitiş değeri)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,5,2)#(Başlama değeri ,bitiş değeri,atalama değeri)

array([0, 2, 4])

*zeros* içerisinde sadece 0 değeri oluşturan bir dizidir

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,2))
# matriks şeklinde 0 lık iki boyutlu bir dizi oluşturabiliriz (matriks istersek 2 tane parantez in içine yazılır)

array([[0., 0.],
       [0., 0.]])

*eye* eydentitiy matriks oluşturur basit olarak çapraz şekilde 1 yazarak oluşturur

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

linspace  belirten sayılar arasında eşit olarak aralık bırakılmış bölerek bir dizi oluşturur

In [ ]:
np.linspace(0,5,10)

#0 da 5 kadar olan sayılırın (float gibi düşünün)10  eşit paraçaya bölümü


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

random rastgele değerler çıkartır burada dikkat etmemiz gerek olay python daki random kütüphanesi ile karıştırılmaması gerektiği numpy içinde olan ayrı bir methodtur

In [ ]:
np.random.randint(1,10,5)
#.randint intger değer döndürür (başlangıç sayısı,en fazla büyüklükteki istediği sayı,kaç tane syı döndürmesi gerektiği)
#,5 olmasydı tek bir değer döndürür.

array([1, 8, 4, 4, 2])

In [ ]:
np.random.rand(5)
#.rand istenilen sayıda bir dizi halinde döndürür  burada random çıktı verdiğinde (+) değeri alabilir.

array([0.38961248, 0.63241083, 0.28913821, 0.75835621, 0.77710103])

In [ ]:
np.random.rand(5,5)
#burada matriks halinde kullanılabilir

array([[0.82623282, 0.09634708, 0.51163431, 0.86483923, 0.73935346],
       [0.11306323, 0.23672237, 0.69999409, 0.30492247, 0.55629702],
       [0.77978923, 0.80935373, 0.83523715, 0.9249668 , 0.34790778],
       [0.89092286, 0.94568643, 0.82457297, 0.02805645, 0.27767645],
       [0.61008372, 0.29382477, 0.15652319, 0.69225964, 0.58333103]])

In [ ]:
np.random.randn(5)
#.randn istenilen sayıda bir dizi halinde döndürür  burada random çıktı verdiğinde (-) değeri alabilir

array([-0.34839176,  0.38655925, -0.9657734 ,  2.74127842, -0.15755299])

In [ ]:
np.random.gamma(5)

#fonksiyonu, gamma dağılımından rastgele örnekler üretmek için kullanılır.
#Parametre olarak şekil parametresi (shape) alır. Bu parametre, gamma dağılımının şeklini belirler.
#np.random.gamma(5) çağrısında, 5 şekil parametresi olarak belirtilmiştir.
#Bu, gamma dağılımının şeklini belirleyen bir parametredir.
#Burada belirtilen sayı ne kadar büyük olursa, gamma dağılımı o kadar geniş ve dışa doğru yayar.


5.296725335258485

In [ ]:
y=np.random.randint(0,100,10)
#burda rastegele dizi üretip bu dizlerin içinde bazı işlemler ypabılırız aşağıda bununla ilgili örnekleri vardır

In [ ]:
y

array([ 8, 70, 90, 42, 92, 43, 24, 43,  1, 40])

In [ ]:
y.mean()

45.3

In [ ]:
y.sum()

453

In [ ]:
y.argmax()
# en yüksek değer sahip olan elemanın index sırasını veririr

4

In [ ]:
det=np.random.randint(1,100,5) # örenk

In [ ]:
det

array([35, 75, 46, 89, 73])

numpy arraylerin indekslenmesi ve parçalnması aynı listedeki indeksleme işelmini burada yapabilriz aynı zamanda aary dizisi içersindede bunları karşılaştırıp koşul olarak kullanabilriz burda ki önemli detay da copy işlemidir copylamada sanki iki farklı liste gibi savranır buda iki listeyi birbirne bağlamdan yazmamızı sağlar

In [1]:
import numpy as np
yy=np.arange(1,10)
yy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
yy[2]#indexler 0 dan başlar burda 2. indeksteki elemanı yazdımak istedim .

3

In [ ]:
yy[1:6] #1.indeksten 6. indekse kadar yazdır ama son yani 6. indeks yazılmaz python da bir kuralldır.

array([2, 3, 4, 5, 6])

In [ ]:
yy[:7] #eğer başında boşluk varsa son daki sayısa kadar bütün indeksleri alır .

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
yy[2:10:3]#2. indeksten başlar 10. indekse kadar gelir fakat : en son yazdığımız değer atlama değeridir.

array([3, 6, 9])

In [4]:
yy[:3]=25
yy #Eğer listenin veya dizinin belirli bir aralığına bir değer atamak istiyorsanız, dilimleme işlemi ile o aralığı seçip, ardından bu seçili aralığa yeni değerler atayabilirsiniz.

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [ ]:
s=np.arange(1,10)
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

*reshape* methodu oluşturulan diziyi istenilen matriks haline getirmemizi  yani yeniden şekilendirmemizi düzenler fakat dikkat etmemiz gereken satır ve sutün sayısının elaman sayısı ile orantılı olmasıdır

In [ ]:
newarr=np.arange(1,21)

In [ ]:
z=newarr.reshape(5,4)
#yeni den ayrı bir değişkene tanımlamayı tercih ettim eğer tanımlamasaydım 2 boyutlu tutmayacaktır.

In [ ]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
z.max()

20

In [ ]:
z.argmin()#argmin() fonksiyonu, bir numpy dizisinde en küçük değere sahip olan elemanın dizindeki indisini döndürür.

0

In [ ]:
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
z[0,0]#burada 0.column 0. row da olan konumdaki elemanı çağırır istediğniz gibi bunun üzerinde oynama yaparak istediğiniz elemanı çağırabilirsiniz .

1

**matrikslerde indexleme **

In [ ]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
z[1,2]#(satır,sutün)[row,column]

7

In [ ]:
z[1:,2]#eğer':' sayının sağ tarıfında ise altnındaki belli olan o sütunun değerleri alir

array([ 7, 11, 15, 19])

In [ ]:
z[1,:2]#1,column kadar gel 2 .satırı dan kesişen yere kadar istenilen alamları çağırır. unutmayın 0 dan başlayark hesaplam yapmalısınız !!!

array([5, 6])

In [ ]:
z[2,3]

12

In [ ]:
z[2:,3]# virgül satır yazılan yerin sağ tarafında ise aşağı doğru satır sayılarını alır bu kısım biraz açıklaması karışıktır fakat biraz üstünde rakamları değiştirerek oynam yaprsınız ne gelmesi gerektiğini anlarsınız .

array([12, 16, 20])

In [ ]:
z[2,:3]

array([ 9, 10, 11])

In [ ]:
z[:2,3]

array([4, 8])

In [ ]:
z[2,3:]

array([12])

In [ ]:
z[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [ ]:
z[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
z[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
z[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
b=np.arange(1,6)

In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
b[b>2]

array([3, 4, 5])

numpy arrylerinin temel operasyonları

In [ ]:
f=np.ones(5)
f

array([1., 1., 1., 1., 1.])

In [ ]:
g=np.zeros(5)
g

array([0., 0., 0., 0., 0.])

In [ ]:
h=np.arange(2,100,2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
j=np.eye(4,4)
j

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
k=np.random.randint(5)
k

2

In [ ]:
m=np.random.randn(25).reshape(5,5)
m

array([[-1.12019783,  1.28399334,  0.42920051, -0.29535053,  0.86267329],
       [ 0.59632782,  0.47489415,  1.0309904 , -0.86065127,  0.39145147],
       [ 0.02607342,  1.15317054, -1.04924684,  0.98860083, -0.49008305],
       [ 1.03618477, -0.59779335, -0.44898139, -1.18818008,  0.82278248],
       [-0.31676885,  0.6041987 , -0.97286546,  0.4688936 ,  1.93116866]])

In [ ]:
import numpy as np
a=np.linspace(1,5,20 )#burada örnek olarak linsace metodu ile bir dizi oluşturduk.

In [ ]:
C=a.copy()
#copy özelliğini kullanarak var olan dizimizi bozmadan aynı diziden bir tane daha elde edip işlem yapabiliriz .

In [ ]:
a

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
C

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [5]:
n=np.arange (5,25)

In [6]:
n

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [7]:
n<20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [8]:
s=np.arange(0,20)

In [9]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
s+s #kendi içerisinde dört işlem yapabilirsiniz.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [11]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
s*s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [13]:
s-s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
s # burda fark edildiği üzere s hiç orjinal hali değişmiyor bu da dizinizn bozmamış olmanıza olanak sağlar.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
s/s #nan değer yazılan  hatalı veya eksik değer anlamına gelir hatalı da olsa bölme işlemine devam eder .

<ipython-input-15-41d9714b9445>:1: RuntimeWarning: invalid value encountered in divide
  s/s


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.sqrt(s)#kareköküne alma fonksiyonur

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [17]:
np.max(s)

19

In [18]:
np.min(s)

0

In [19]:
d=np.array([1,2,3,4,5,6])
c=np.array([10,20,30,40,50,60])


In [20]:
d+c

#burada eleman sayısı eşit olmalıdır .her bir eleman indeksleri dört işlemi tamamlar

array([11, 22, 33, 44, 55, 66])

In [21]:
d*10

array([10, 20, 30, 40, 50, 60])

In [22]:
d

array([1, 2, 3, 4, 5, 6])

In [23]:
np.sqrt(d)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [24]:
c

array([10, 20, 30, 40, 50, 60])